AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # as per vgg16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHT: imagenet
LEARNING_RATE: 0.01
OPTIMIZER : Adam()
LOSS: categorical_crossentropy
METRICS: ['accuracy']


